use rmcp::{ErrorData as McpError, model::*};
use serde_json::json;

use crate::state::SharedState;
use super::{make_tool, text_result, error_result};

pub fn tools() -> Vec<Tool> {
    vec![make_tool(
        "merge_scenario",
        "Merge all accumulated state into a complete scenario YAML string. \
         Returns the full YAML that can be saved as a .yaml file and loaded into FinPlan. \
         Call validate_scenario first to check for errors.",
        json!({
            "type": "object",
            "properties": {}
        }),
    )]
}

pub fn merge_scenario(state: &SharedState) -> Result<CallToolResult, McpError> {
    let st = state.lock().unwrap();

    match st.merge() {
        Ok(sim_data) => {
            match serde_saphyr::to_string(&sim_data) {
                Ok(yaml) => text_result(format!(
                    "# FinPlan Scenario YAML\n# Generated by finplan-mcp\n\n{}",
                    yaml
                )),
                Err(e) => error_result(format!("Failed to serialize to YAML: {}", e)),
            }
        }
        Err(errors) => error_result(format!(
            "Cannot merge scenario:\n{}",
            errors.join("\n")
        )),
    }
}
